<!-- bower:js -->
<script src="/bower_components/angular/angular.js"></script>
<script src="/bower_components/angular-translate/angular-translate.js"></script>
<!-- endinject -->
<!-- inject:js -->
<script src="/app/main.module.js"></script>
<script src="/app/core/core.module.js"></script>
<script src="/app/demo/demo.module.js"></script>
<script src="/app/core/core.config.js"></script>
<script src="/app/demo/demo.controller.js"></script>
<script src="/app/demo/demo.directive.js"></script>
<script src="/app/demo/demo.service.js"></script>
<!-- endinject -->